version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - ../wp-mysql:/var/lib/mysql
    command: 
      '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network


  nginx:
    depends_on:
      - mysql
      - wp
    build: nginx/
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - $HTTP_PORT:80
      - $HTTPS_PORT:443
    volumes:
     - ./nginx/configs/conf.d/:/etc/nginx/conf.d/
     - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/ssl/:/etc/nginx/ssl/
     - ./nginx/configs/.htpasswd:/etc/nginx/.htpasswd
     - ./wordpress:/var/www/html

    networks:
      - app-network

  wp:
    image: wordpress:php8.2-fpm-alpine
    container_name: wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_HOST=mysql
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
